# Default initial positions for omtp_factory's ros2_control fake system

initial_positions:
  panda1_joint1: 0
  panda1_joint2: 0
  panda1_joint3: 0
  panda1_joint4: -1.5708
  panda1_joint5: 0
  panda1_joint6: 1.5708
  panda1_joint7: -0.7854
  panda2_joint1: 0
  panda2_joint2: 0
  panda2_joint3: 0
  panda2_joint4: -1.5708
  panda2_joint5: 0
  panda2_joint6: 1.5708
  panda2_joint7: -0.7854
