# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    panda1_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    panda2_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

panda1_arm_controller:
  ros__parameters:
    joints:
      - panda1_joint1
      - panda1_joint2
      - panda1_joint3
      - panda1_joint4
      - panda1_joint5
      - panda1_joint6
      - panda1_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
panda2_arm_controller:
  ros__parameters:
    joints:
      - panda2_joint1
      - panda2_joint2
      - panda2_joint3
      - panda2_joint4
      - panda2_joint5
      - panda2_joint6
      - panda2_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity