# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    panda_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

panda_arm_controller:
  ros__parameters:
    joints:
      - panda1_joint1
      - panda1_joint2
      - panda1_joint3
      - panda1_joint4
      - panda1_joint5
      - panda1_joint6
      - panda1_joint7
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    gains:
      panda1_joint1:
        p: 30000.0
        i: 1.0
        d: 150.0
        angle_wrap_around: false
        i_clamp: 1.0
        ff_velocity_scale: 1.0
      panda1_joint2:
        p: 30000.0
        i: 1.0
        d: 100.0
        angle_wrap_around: false
        i_clamp: 1.0
        ff_velocity_scale: 1.0
      panda1_joint3:
        p: 20000.0
        i: 1.0
        d: 100.0
        angle_wrap_around: false
        i_clamp: 1.0
        ff_velocity_scale: 1.0
      panda1_joint4:
        p: 18000.0
        i: 1.0
        d: 100.0
        angle_wrap_around: false
        i_clamp: 1.0
        ff_velocity_scale: 1.0
      panda1_joint5:
        p: 12000.0
        i: 1.0
        d: 100.0
        angle_wrap_around: false
        i_clamp: 1.0
        ff_velocity_scale: 1.0
      panda1_joint6:
        p: 10000.0
        i: 1.0
        d: 100.0
        angle_wrap_around: false
        i_clamp: 1.0
        ff_velocity_scale: 1.0
      panda1_joint7:
        p: 8000.0
        i: 1.0
        d: 100.0
        angle_wrap_around: false
        i_clamp: 1.0
        ff_velocity_scale: 1.0
hand_controller:
  ros__parameters:
    joints:
      - panda1_finger_joint1
      - panda1_finger_joint2
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    gains:
      panda1_finger_joint1:
        p: 100.0
        i: 10.0
        d: 10.0
        angle_wrap_around: false
        i_clamp: 1.0
        ff_velocity_scale: 1.0
      panda1_finger_joint2:
        p: 100.0
        i: 10.0
        d: 10.0
        angle_wrap_around: false
        i_clamp: 1.0
        ff_velocity_scale: 1.0
